### ISSUE TITLE
Return-path not possible automatically?

### ISSUE THREAD

**Issue by ccoenen** [corentinway/shortest-way#1]
Is it intentional, that A -> B does not automatically mean B -> A? If so, is there a convenience function to set the pairs up automatically? Also the output (provided at the end) seems to be wrong?

```JavaScript
var Node = require( 'shortest-way' ).Node;

// create nodes 
var nodes = {
	startNode: new Node( { id: 'startNode' } ),
	middleNode1: new Node( { id: 'middleNode1' } ),
	middleNode2: new Node( { id: 'middleNode2' } ),
	middleNode3: new Node( { id: 'middleNode3' } ),
	endNode: new Node( { id: 'endNode' } )
};

// add relation
nodes.startNode.addNext(nodes.middleNode1, 1.9);
nodes.startNode.addNext(nodes.middleNode2, 1.7);
nodes.middleNode1.addNext(nodes.endNode, 1);
nodes.middleNode2.addNext(nodes.middleNode3, 0.01);
nodes.middleNode3.addNext(nodes.endNode, 1);

// Test 1: array!
console.log("from array\n=====================");
var pathFromArray = nodes.endNode.compute(nodes.startNode, [nodes.startNode, nodes.middleNode1, nodes.middleNode2, nodes.middleNode3, nodes.endNode]);
console.log(pathFromArray.map(function (item,index) {return index + ': ' + item.id;}).join("\n"));

// Test 2: object!
console.log("\nfrom object\n=====================");
var pathFromObject = nodes.endNode.compute(nodes.startNode, nodes);
console.log(pathFromObject.map(function (item,index) {return index + ': ' + item.id;}).join("\n"));
```

**expected output:**
0: endNode
1: middleNode3
2: middleNode2
3: startNode

**actual output:**
0: endNode
1: startNode

So, as you can see, the actual output from shortest-way is not only not the expected result, it's the same result as if there was no actual path (which currently is not reported either, but this is a question for #2 )

**Comment by klntsky** [comment]
```
nodes.endNode.compute(nodes.startNode, nodes);
```
Wrong.

README says:
```
var result = startNode.compute( endNode, allNodes );
```

You need to swap `nodes.startNode` and `nodes.endNode` 

> Is it intentional, that A -> B does not automatically mean B -> A?

Yes, because we're talking about *directed* graphs.

> If so, is there a convenience function to set the pairs up automatically?

No, there is not. Write it yourself.

**Comment by ccoenen** [comment]
>> nodes.endNode.compute(nodes.startNode, nodes);
> Wrong. [...readme...swapping...]

No it is not _wrong_. As you probably saw, my entire question revolves around a graph working both ways. I illustrated that by using one simple graph and running the algorithm in reverse direction. The start/end swapping was no accident on my part.

The readme claims that this is an implementation of Dijkstra's algorithm, which is not limited to directed graphs. There is one single place in the readme that hints at directed graphs (building the graph section). The name of this module is "shortest-way" which also does not hint at directedness. It hardly strikes me as a design decision to base this on directed graphs, more like something that simply "happened" during implementation. There is no good reason why this package couldn't simply add a facility like that.

Short: I still think, this library should not be limited to _directed_ graphs.

Finally, I would like to point out that I'm having a very hard time imagining your reply in a friendly tone of voice. I have no idea if that is intentional or if there's a barrier of language involved. In case you came here to help me: thank you for taking the time.

**Comment by 8084** [comment]
I've forked the repo and made some changes that look like a fix for the problem mentioned in #2 , and also I've added `connectWith` function to `Node`s protoype which should be used when dealing with inderected graphs.

https://github.com/8084/shortest-way

**Comment by klntsky** [comment]
@ccoenen, check out #3

**Comment by corentinway** [comment]
Check pull request #1
