### ISSUE TITLE
Impossible routes do not look that way

### ISSUE THREAD

**Issue by ccoenen** [corentinway/shortest-way#2]
An impossible route should be distinguishable from a possible one. If this is achieved by an exception (which one would have to catch) or by an explicit error return (like ´null`) or just an empty array, is not important but it should do one of those.

Right now, this happens, note that the two nodes are NOT connected intentionally:

```JavaScript
var Node = require( 'shortest-way' ).Node;

// create nodes
var n1 = new Node( { id: 'n1' } );
var n2 = new Node( { id: 'n2' } );

var path = n1.compute(n2, [n1, n2]);
console.log(path.map(function (item,index) {return index + ': ' + item.id;}).join("\n"));
```

**expected result**
`null` or `[]` or some kind of Exception

**actual result**
0: n1
1: n2

The printed result is indistinguishable from a connected graph, as far as I can tell.

**Comment by corentinway** [comment]
Thank you. I will have a look at it.

**Comment by corentinway** [comment]
Check pull request #1
